spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/testdb
    username: brant
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
